ERROR - 2023-09-21 02:52:15 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\code_4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\code_4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'code', 3306, '', 0)
#1 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\code_4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\code_4\app\Models\newmodel.php(23): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\code_4\app\Controllers\Newhome.php(44): App\Models\newmodel->selectrow('members')
#6 C:\xampp\htdocs\code_4\system\CodeIgniter.php(919): App\Controllers\Newhome->dase()
#7 C:\xampp\htdocs\code_4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Newhome))
#8 C:\xampp\htdocs\code_4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\code_4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\code_4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\code_4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\code_4\app\Models\newmodel.php(23): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\code_4\app\Controllers\Newhome.php(44): App\Models\newmodel->selectrow('members')
#5 C:\xampp\htdocs\code_4\system\CodeIgniter.php(919): App\Controllers\Newhome->dase()
#6 C:\xampp\htdocs\code_4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Newhome))
#7 C:\xampp\htdocs\code_4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\code_4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-09-21 02:52:15 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `members`', [], false)
 3 APPPATH\Models\newmodel.php(23): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Newhome.php(44): App\Models\newmodel->selectrow('members')
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Newhome->dase()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Newhome))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-09-21 02:52:20 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\code_4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\code_4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'code', 3306, '', 0)
#1 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\code_4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\code_4\app\Models\newmodel.php(23): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\code_4\app\Controllers\Newhome.php(44): App\Models\newmodel->selectrow('members')
#6 C:\xampp\htdocs\code_4\system\CodeIgniter.php(919): App\Controllers\Newhome->dase()
#7 C:\xampp\htdocs\code_4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Newhome))
#8 C:\xampp\htdocs\code_4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\code_4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\code_4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\code_4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\code_4\app\Models\newmodel.php(23): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\code_4\app\Controllers\Newhome.php(44): App\Models\newmodel->selectrow('members')
#5 C:\xampp\htdocs\code_4\system\CodeIgniter.php(919): App\Controllers\Newhome->dase()
#6 C:\xampp\htdocs\code_4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Newhome))
#7 C:\xampp\htdocs\code_4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\code_4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-09-21 02:52:20 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `members`', [], false)
 3 APPPATH\Models\newmodel.php(23): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Newhome.php(44): App\Models\newmodel->selectrow('members')
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Newhome->dase()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Newhome))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-09-21 02:52:25 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\code_4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\code_4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'code', 3306, '', 0)
#1 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\code_4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\code_4\app\Models\newmodel.php(23): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\code_4\app\Controllers\Newhome.php(44): App\Models\newmodel->selectrow('members')
#6 C:\xampp\htdocs\code_4\system\CodeIgniter.php(919): App\Controllers\Newhome->dase()
#7 C:\xampp\htdocs\code_4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Newhome))
#8 C:\xampp\htdocs\code_4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\code_4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\code_4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\code_4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\code_4\app\Models\newmodel.php(23): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\code_4\app\Controllers\Newhome.php(44): App\Models\newmodel->selectrow('members')
#5 C:\xampp\htdocs\code_4\system\CodeIgniter.php(919): App\Controllers\Newhome->dase()
#6 C:\xampp\htdocs\code_4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Newhome))
#7 C:\xampp\htdocs\code_4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\code_4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-09-21 02:52:25 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `members`', [], false)
 3 APPPATH\Models\newmodel.php(23): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Newhome.php(44): App\Models\newmodel->selectrow('members')
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Newhome->dase()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Newhome))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-09-21 02:52:38 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\code_4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\code_4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'code', 3306, '', 0)
#1 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\code_4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\code_4\app\Models\newmodel.php(44): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\code_4\app\Controllers\Newhome.php(32): App\Models\newmodel->check('users', Array)
#6 C:\xampp\htdocs\code_4\system\CodeIgniter.php(919): App\Controllers\Newhome->index()
#7 C:\xampp\htdocs\code_4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Newhome))
#8 C:\xampp\htdocs\code_4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\code_4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\code_4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\code_4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\code_4\app\Models\newmodel.php(44): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\code_4\app\Controllers\Newhome.php(32): App\Models\newmodel->check('users', Array)
#5 C:\xampp\htdocs\code_4\system\CodeIgniter.php(919): App\Controllers\Newhome->index()
#6 C:\xampp\htdocs\code_4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Newhome))
#7 C:\xampp\htdocs\code_4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\code_4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-09-21 02:52:38 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `name` = :name:
AND `pass` = :pass:', [...], false)
 3 APPPATH\Models\newmodel.php(44): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Newhome.php(32): App\Models\newmodel->check('users', [...])
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Newhome->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Newhome))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-09-21 05:25:57 --> mysqli_sql_exception: Table 'code.code1' doesn't exist in C:\xampp\htdocs\code_4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\code_4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\code_4\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\code_4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\code_4\app\Models\newmodel.php(36): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\code_4\app\Controllers\Home.php(37): App\Models\newmodel->selectonerow('code1', Array)
#6 C:\xampp\htdocs\code_4\system\CodeIgniter.php(919): App\Controllers\Home->update('6')
#7 C:\xampp\htdocs\code_4\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\code_4\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\code_4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-09-21 05:25:57 --> Table 'code.code1' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `code1`
WHERE `row` = :row:', [...], false)
 2 APPPATH\Models\newmodel.php(36): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Home.php(37): App\Models\newmodel->selectonerow('code1', [...])
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Home->update('6')
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-21 05:30:39 --> Undefined property: stdClass::$age
in APPPATH\Views\my_view\insert.php on line 175.
 1 APPPATH\Views\my_view\insert.php(175): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$age', 'C:\\xampp\\htdocs\\code_4\\app\\Views\\my_view\\insert.php', 175)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\code_4\\app\\Views\\my_view\\insert.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('my_view/insert', [], true)
 5 APPPATH\Controllers\Home.php(39): view('my_view/insert', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Home->update('4')
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-21 05:30:44 --> Undefined property: stdClass::$age
in APPPATH\Views\my_view\insert.php on line 175.
 1 APPPATH\Views\my_view\insert.php(175): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$age', 'C:\\xampp\\htdocs\\code_4\\app\\Views\\my_view\\insert.php', 175)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\code_4\\app\\Views\\my_view\\insert.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1188): CodeIgniter\View\View->render('my_view/insert', [], true)
 5 APPPATH\Controllers\Home.php(39): view('my_view/insert', [...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Home->update('7')
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
